wandb_project_name: maddpg-final
total_steps: 7_500_000
max_episode_length: 25
hidden_dim_width: 64
critic_lr: 3.e-4
actor_lr: 3.e-4
policy_regulariser: 0.001
standardise_rewards: True
save_agents: True
#offline_wandb: True
